In [1]:
print("Hello world")

Hello world


In [2]:
list(range(20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [4]:
set={range(10)}

In [5]:
set

{range(0, 10)}

In [6]:
print(set)

{range(0, 10)}


In [9]:
my_string = "this is demo"
for mobin in my_string:
    print(mobin)

t
h
i
s
 
i
s
 
d
e
m
o


In [10]:
i=1
while(i<=10):
    print(i*i)
    print(i*i*i)
    i=i+1

1
1
4
8
9
27
16
64
25
125
36
216
49
343
64
512
81
729
100
1000


In [11]:
for i in range(100,1,-4):
    print(i)

100
96
92
88
84
80
76
72
68
64
60
56
52
48
44
40
36
32
28
24
20
16
12
8
4


In [1]:
num =int(input("enter height "))
for i in range(num):
    print("@"*i)
       

ValueError: invalid literal for int() with base 10: ''

In [2]:
for i in range(4):
    for j in range(i):
        print("@",end="")
    print("@")    

@
@@
@@@
@@@@


In [1]:
password=input("Enter the password: ")
for i in range(5):
    

SyntaxError: incomplete input (1804016562.py, line 3)

In [2]:
def test():
    pass

In [3]:
type(test())

NoneType

In [4]:
def add():
    a=1
    b=2
    print(a+b)
add()    

3


In [6]:
add()

3


In [7]:
type(add())

3


NoneType

In [8]:
def add(a,b):
    return str(a)+str(b)
    

In [9]:
add(3,4)

'34'

In [10]:
import numpy


In [11]:
def my_fun():
    x=10
    print("value inside Function:",x)
x=20
my_fun()
print("value outside the fun:",x)    

value inside Function: 10
value outside the fun: 20


In [22]:
list=['karan','kuadadaanj','vermasjfma','sharma','darpan']
print(list) 

def company():
    x=len(list[0])
    for i in list:
        if(len(i)>x):
            x=len(i)
            y=i  
    print("highest name in list is :",y,": with lenght :",x)
company()    


['karan', 'kuadadaanj', 'vermasjfma', 'sharma', 'darpan']
highest name in list is : kuadadaanj : with lenght : 10


In [23]:
cube= lambda x:x**3

In [24]:
cube(7)

343

In [27]:
for i in range(5):
    list[input("Enter the numbers: ")]
even= lambda     

TypeError: list indices must be integers or slices, not str

In [1]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
import numpy as np  
for i in range(5):
    arr= np.array(input([i]))
for i in arr:    
    print(i)
print(type(arr))

TypeError: iteration over a 0-d array

In [9]:
print(np.__version__)

1.23.3


In [1]:
import numpy as np

In [2]:
numpy.--version--

SyntaxError: invalid syntax (1365612055.py, line 1)

In [3]:
numpy.__version__

NameError: name 'numpy' is not defined

In [4]:
np.__version__

'1.23.3'

In [ ]:
def Hello():
    print("Hello World! ")
Hello()    

In [23]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr1.sum()
np.average(arr1) #axis for row and cloumn wise,axis=0,1
arr1.min()
arr1.max()
arr1.mean()
arr=np.array([[1,2,3],[5,6,7],[9,10,11]])
arr.mean(0)
arr.sum(axis=0)



array([15, 18, 21])

In [29]:
# Broadcasting
arr_rand=np.random.randint(10,50, size = (5,8))
arr_rand
arr1_rand=np.random.randint(1,20,size=(2,3,6)) #2 for split in 2
arr1_rand
arr1_rand.ndim

3

In [33]:
np.greater_equal(arr,2)

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [34]:
a=np.arange(10)
i=np.array([2,1,8,4])
a[i]=99
print(a)

[ 0 99 99  3 99  5  6  7 99  9]


In [35]:
a=np.zeros(10)
a[[0,0]]=[2,8]
print(a)

[8. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
