In [11]:
### 1. Write a Python Program to Add Two Matrices?
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([[6,5,4],[3,2,1]])
print("Matrix before multiply")
print(arr)
print(arr1)
print("Matrix after multiply")
multi=arr.dot(arr1)
print(multi)




Matrix before multiply
[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]
Matrix after multiply


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)